# workflow definition
name: Init Repo Labels

# workflow trigger definition
on: 
  workflow_dispatch:  # manually triggered

# workflow job(s) definition
jobs:
  job-1:
    # define platform required for job
    runs-on: ubuntu-latest
    # description of function performed by the job
    name: creating standard labels in ${{github.event.repository.name}}
    
    # steps executed by job
    steps:
    - run: echo "Git hub context ${{toJson(github.event)}}"  # [debug] dump trigger event context info
    # execute job action(s)
    - name: create labels
      id: init-repo
      # call script defined in <owner>/<repo>/<script> and by @<release> or @<branch>
      uses: vvec/init-repo@main
      # with parameters defined ../<repo>/<script>/action.yml
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        repo-id: ${{github.event.repository.node_id}}
        repo-name: ${{github.event.repository.name}}
        repo-owner: ${{github.event.repository.owner.login}}