# workflow definition
name: Init Repo Labels

# workflow trigger definition
on: 
  workflow_dispatch:  # manually triggered

# workflow job(s) definition
jobs:
  job-1:
    # define platform required for job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]    
    # description of function performed by the job
    name: creating standard labels in ${{github.event.repository.name}}
    
    # steps executed by job
    steps:
    - run: echo "Git hub context ${{toJson(github.event)}}"  # [debug] dump trigger event context info
    # @ todo: figure out how to setup node enviroment
#     - uses: actions/setup-node@v3
#       with:
#         node-version: lts/*
#     - run: npm ci
#     - run: npm test
  # execute job action(s)
    - name: create labels
      id: init-repo
      # call script defined in <owner>/<repo>/<script> and by @<release> or @<branch>
      uses: vvec/init-repo@main
      # with parameters defined ../<repo>/<script>/action.yml
      with:
        node-version: ${{ matrix.node-version }}
        repo-token: ${{secrets.GITHUB_TOKEN}}
        repo-id: ${{github.event.repository.node_id}}
        repo-name: ${{github.event.repository.name}}
        repo-owner: ${{github.event.repository.owner.login}}
